- name: è…¾è®¯äº‘
  url: https://cloud.tencent.com/
  img: /images/qcloud.png
  description: äº‘æœåŠ¡å™¨ & DNSPod
- name: é˜¿é‡Œäº‘
  url: https://www.aliyun.com/
  img: /images/aliyun.png
  description: æœ¬ç«™åŸŸåè´­è‡ªé˜¿é‡Œäº‘
- name: Cloudflare
  url: https://www.cloudflare.com/zh-cn/
  img: /images/cloudflare.png
  description: åŸŸåã€æŠ—æ”»å‡»ä¸ Cloudflare Pages
- name: Vercel
  url: https://vercel.com/
  img: /images/vercel.png
  description: Web åº”ç”¨éƒ¨ç½²
- name: Docker ğŸ†“
  url: https://docs.docker.com/engine/
  img: /images/docker.png
  description: åº”ç”¨å®¹å™¨å¼•æ“
- name: Discuz!
  url: https://www.discuz.vip/
  img: /images/discuzx.png
  description: å›½å†…å¤§éƒ¨åˆ†è®ºå›ä½¿ç”¨çš„è½¯ä»¶
- name: Flarum ğŸ†“
  url: https://flarum.org.cn/
  img: /images/flarum.png
  description: ä¼˜é›…ç®€æ´çš„è½»è®ºå›
- name: MediaWiki ğŸ†“âœˆï¸â“
  url: https://www.mediawiki.org/
  img: /images/mediawiki.png
  description: é©±åŠ¨ Wikipedia çš„è½¯ä»¶
- name: Hexo ğŸ†“
  url: https://hexo.io/
  img: /images/hexo.png
  description: æœ¬ç«™å’Œç«™é•¿çš„åšå®¢ä½¿ç”¨çš„æ¡†æ¶
- name: VuePress ğŸ†“
  url: https://vuepress.vuejs.org/zh/
  img: /images/vuepress.png
  description: Vue é©±åŠ¨çš„é™æ€ç½‘ç«™ç”Ÿæˆå™¨
- name: WordPress ğŸ†“
  url: https://cn.wordpress.org/download/
  img: /images/wordpress.png
  description: å…¨çƒç”¨æˆ·é‡æœ€å¤šçš„ CMS ç³»ç»Ÿ
- name: Typecho ğŸ†“
  url: http://typecho.org/download
  img: /images/typecho.png
  description: è½»é‡çº§ PHP åšå®¢ç¨‹åº
- name: Gitea ğŸ†“
  url: https://gitea.io/zh-cn/
  img: /images/gitea.png
  description: è½»é‡çº§ä»£ç æ‰˜ç®¡è§£å†³æ–¹æ¡ˆ
- name: frp ğŸ†“
  url: https://github.com/fatedier/frp
  img: /images/frp.png
  description: ä¸€ä¸ªä¸“æ³¨äºå†…ç½‘ç©¿é€çš„åå‘ä»£ç†åº”ç”¨
- name: UptimeRobot
  url: https://uptimerobot.com/
  img: /images/uptimerobot.png
  description: ç½‘ç«™åœ¨çº¿çŠ¶æ€ç›‘æµ‹
- name: BestTrace
  url: https://www.ipip.net/product/client.html
  img: /images/besttrace.png
  description: å‘èµ· traceroute è¯·æ±‚ï¼Œé™„å¸¦é“¾è·¯å¯è§†åŒ–
- name: ç™¾åº¦è´´å§äº‘ç­¾åˆ°
  url: https://github.com/MoeNetwork/Tieba-Cloud-Sign
  img: /images/cloudsign.png
  description: éƒ¨ç½²åå®ç°è´´å§å…¨è‡ªåŠ¨ç­¾åˆ°