- name: è…¾è®¯äº‘
  url: https://cloud.tencent.com/
  img: /images/logos/qcloud.png
  description: äº‘æœåŠ¡å™¨ & DNSPod
- name: é˜¿é‡Œäº‘
  url: https://www.aliyun.com/
  img: /images/logos/aliyun.png
  description: æœ¬ç«™åŸŸåè´­è‡ªé˜¿é‡Œäº‘
- name: Cloudflare
  url: https://www.cloudflare.com/zh-cn/
  img: /images/logos/cloudflare.png
  description: åŸŸåã€æŠ—æ”»å‡»ä¸ Cloudflare Pages
- name: Vercel
  url: https://vercel.com/
  img: /images/logos/vercel.png
  description: Web åº”ç”¨éƒ¨ç½²
- name: Docker
  url: https://docs.docker.com/engine/
  img: /images/logos/docker.png
  description: ğŸ†“å¼€æºåº”ç”¨å®¹å™¨å¼•æ“
- name: Discuz!
  url: https://www.discuz.vip/
  img: /images/logos/discuzx.png
  description: å›½å†…å¤§éƒ¨åˆ†è®ºå›ä½¿ç”¨çš„è½¯ä»¶
- name: Flarum
  url: https://flarum.org.cn/
  img: /images/logos/flarum.png
  description: ğŸ†“ä¼˜é›…ç®€æ´çš„è½»è®ºå›
- name: MediaWiki
  url: https://www.mediawiki.org/
  img: /images/logos/mediawiki.png
  description: ğŸ†“é©±åŠ¨ Wikipedia çš„è½¯ä»¶ (å¯èƒ½éœ€ä»£ç†)
- name: Hexo
  url: https://hexo.io/
  img: /images/logos/hexo.png
  description: ğŸ†“æœ¬ç«™å’Œç«™é•¿çš„åšå®¢ä½¿ç”¨çš„æ¡†æ¶
- name: VuePress
  url: https://vuepress.vuejs.org/zh/
  img: /images/logos/vuepress.png
  description: ğŸ†“Vue é©±åŠ¨çš„é™æ€ç½‘ç«™ç”Ÿæˆå™¨
- name: WordPress
  url: https://cn.wordpress.org/download/
  img: /images/logos/wordpress.png
  description: ğŸ†“å…¨çƒç”¨æˆ·é‡æœ€å¤šçš„ CMS ç³»ç»Ÿ
- name: Typecho
  url: http://typecho.org/download
  img: /images/logos/typecho.png
  description: ğŸ†“è½»é‡çº§ PHP åšå®¢ç¨‹åº
- name: AList
  url: https://github.com/alist-org/alist
  img: /images/logos/alist.png
  description: ğŸ†“æ”¯æŒå¤šå­˜å‚¨çš„æ–‡ä»¶åˆ—è¡¨ç¨‹åº
- name: Gitea
  url: https://gitea.io/zh-cn/
  img: /images/logos/gitea.png
  description: ğŸ†“è½»é‡çº§ä»£ç æ‰˜ç®¡è§£å†³æ–¹æ¡ˆ
- name: frp
  url: https://github.com/fatedier/frp
  img: /images/logos/frp.png
  description: ğŸ†“ä¸€ä¸ªä¸“æ³¨äºå†…ç½‘ç©¿é€çš„åå‘ä»£ç†åº”ç”¨
- name: UptimeRobot
  url: https://uptimerobot.com/
  img: /images/logos/uptimerobot.png
  description: ç½‘ç«™åœ¨çº¿çŠ¶æ€ç›‘æµ‹
- name: BestTrace
  url: https://www.ipip.net/product/client.html
  img: /images/logos/besttrace.png
  description: å‘èµ· traceroute è¯·æ±‚ï¼Œé™„å¸¦é“¾è·¯å¯è§†åŒ–
- name: ç™¾åº¦è´´å§äº‘ç­¾åˆ°
  url: https://github.com/MoeNetwork/Tieba-Cloud-Sign
  img: /images/logos/cloudsign.png
  description: éƒ¨ç½²åå®ç°è´´å§å…¨è‡ªåŠ¨ç­¾åˆ°